"""
services/report_service.py — Clinical report generation for AI predictions
"""
import datetime


def generate_prediction_report(prediction_data: dict, doctor_name: str = "Dr. Attending", patient_name: str = "Patient") -> str:
    """
    Generate a plain-text clinical report for an AI prediction result.
    Returns the report as a multi-line string.
    """
    now = datetime.datetime.utcnow()
    sep = "=" * 62

    lines = [
        sep,
        "    ONCOLENS AI CANCER PREDICTION REPORT",
        "    Powered by OnchoLens CNN (MobileNetV2-based)",
        sep,
        "",
        f"  Report Generated : {now.strftime('%Y-%m-%d %H:%M:%S')} UTC",
        f"  Record ID        : {prediction_data.get('record_id', 'N/A')}",
        f"  Attending Doctor : {doctor_name}",
        f"  Patient          : {patient_name}",
        "",
        "─" * 62,
        "  PREDICTION RESULTS",
        "─" * 62,
        "",
        f"  Outcome          : {prediction_data.get('prediction', '—')}",
        f"  Cancer Detected  : {'YES ⚠️' if prediction_data.get('detected') else 'NO ✅'}",
        f"  Confidence Score : {prediction_data.get('confidence', 0):.1f}%",
        f"  Cancer Prob.     : {prediction_data.get('probability', 0) * 100:.2f}%",
        f"  Risk Level       : {prediction_data.get('risk_level', '—')}",
        f"  Risk Tier        : {prediction_data.get('risk_tier', '—').upper()}",
        "",
        "─" * 62,
        "  MODEL INFORMATION",
        "─" * 62,
        "",
        "  Model Name       : OnchoLens CNN",
        "  Architecture     : MobileNetV2 (fine-tuned)",
        "  Input Resolution : 224 × 224 px",
        "  Output Layer     : Sigmoid (binary classification)",
        "  Training Dataset : Proprietary oncology scan dataset",
        "",
        "─" * 62,
        "  RISK INTERPRETATION",
        "─" * 62,
        "",
        "  Tier       | Probability Range | Recommended Action",
        "  -----------|-------------------|---------------------------",
        "  Benign     | 0% – 29%          | Routine follow-up",
        "  Low Risk   | 30% – 49%         | Closer monitoring advised",
        "  Moderate   | 50% – 79%         | Specialist consultation",
        "  High Risk  | 80% – 100%        | Urgent clinical review",
        "",
        "─" * 62,
        "  ⚠️  CLINICAL DISCLAIMER",
        "─" * 62,
        "",
        "  This report is generated by an AI decision-support system",
        "  and must NOT be used as the sole basis for clinical decisions.",
        "  Always validate results with a qualified medical professional,",
        "  additional diagnostic imaging, and patient history.",
        "",
        "  OnchoLens is a DECISION-SUPPORT tool, not a diagnostic device.",
        "",
        sep,
        f"  © {now.year} OnchoLens Healthcare AI Platform",
        sep,
    ]

    return "\n".join(lines)
